name: Run tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.22.11
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: yarn
      - name: Run tests
        run: yarn test
